### ISSUE TITLE
Loading of partials in mustache templates is OS dependent

### ISSUE THREAD

**Issue by akloeber** [sviperll/ozymandias#6]
When loading partials in a mustache template via `{{> somePartial}}` the path to be used for referencing the partial depends on the OS.

On Mac OS X and Unix a partial named `somePartial.mustache` that resides in the same directory can be referenced as expected via `{{> somePartial}}`, so the path is evaluated relative to the template file where the partial is used.

On Windows the path has to be configured relative to the projects root directory which is where the `pom.xml` resides: `{{> src/main/resources/somePartial}}`.

This makes it hard to make the plugin work across all platforms.

Tested with mustache-maven-plugin@v0.22 on:
Windows 7
Max OS X 10.11.3
Red Hat Enterprise Linux Server release 6.7 (Santiago)

**Comment by sviperll** [comment]
Mac OS X and Linux expose "right" behaviour. Can you provide an error that is produced on Windows machine for missing partial?

**Comment by akloeber** [comment]
Here is the debug output of Maven:

```
[ERROR] Failed to execute goal com.github.sviperll:mustache-maven-plugin:0.22:render (default) on project backend: Execution default of goal com.github.sviperll:mustache-maven-plugin:0.22:render failed: Template header.partial.mustache not found -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.sviperll:mustache-maven-plugin:0.22:render (default) on project backend: Execution default of goal com.github.sviperll:mustache-maven-plugin:0.22:render failed: Template header.partial.mustache not found
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.github.sviperll:mustache-maven-plugin:0.22:render failed: Template header.partial.mustache not found
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
Caused by: com.github.mustachejava.MustacheNotFoundException: Template header.partial.mustache not found
        at com.github.mustachejava.DefaultMustacheFactory.getReader(DefaultMustacheFactory.java:112)
        at com.github.mustachejava.MustacheParser.compile(MustacheParser.java:27)
        at com.github.mustachejava.DefaultMustacheFactory.compilePartial(DefaultMustacheFactory.java:250)
        at com.github.mustachejava.codes.PartialCode.init(PartialCode.java:70)
        at com.github.mustachejava.codes.DefaultCode.init(DefaultCode.java:118)
        at com.github.mustachejava.codes.DefaultMustache.init(DefaultMustache.java:64)
        at com.github.mustachejava.DefaultMustacheFactory.compile(DefaultMustacheFactory.java:198)
        at com.github.mustachejava.DefaultMustacheFactory.compile(DefaultMustacheFactory.java:192)
        at com.github.sviperll.maven.plugin.mustache.MustacheLoader.load(MustacheLoader.java:39)
        at com.github.sviperll.maven.plugin.mustache.RenderMustacheMojo.execute(RenderMustacheMojo.java:34)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
```

**Comment by sviperll** [comment]
Please test ozymandias-0.23-rc1. It should work as expected on both Linux and Windows.

**Comment by akloeber** [comment]
I will, but it'll take some time as I do not have access to a Windows machine right now.

**Comment by akloeber** [comment]
I just checked it on Windows and it works fine with v0.23-rc1.
Thanks a lot!
